### ISSUE TITLE
footer designs [DESKTOP]

### ISSUE THREAD

**Issue by tanmoy27112000** [tanmoy27112000/flutter_web_base#2]
Design : https://getbootstrap.com/docs/5.3/examples/footers/

**Comment by chandansgowda** [comment]
Please assign me @tanmoy27112000

**Comment by chandansgowda** [comment]
Also, please help me with setting up the environment. Coz I'm getting this error when I'm trying to build the project.
<img width="1404" alt="Screenshot 2022-12-22 at 9 11 14 PM" src="https://user-images.githubusercontent.com/41890434/209170221-dbeb8242-d6b5-469b-8817-8cc89042de4d.png">

**Comment by tanmoy27112000** [comment]
@chandansgowda  please connect with me in the discord channel and we can fix the issue.

**Comment by tanmoy27112000** [comment]
The design you need to replicate : https://getbootstrap.com/docs/5.3/examples/footers/

**Comment by YuvrajSingh3110** [comment]
Hey @tanmoy27112000 i would like to work on this, assign me under JWOC

**Comment by tanmoy27112000** [comment]
@YuvrajSingh3110 you can start working on the design
