### ISSUE TITLE
grid view with hover effect

### ISSUE THREAD

**Issue by tanmoy27112000** [tanmoy27112000/flutter_web_base#5]

**Comment by Tushar98644** [comment]
assign me @tanmoy27112000

**Comment by avirupnandi1** [comment]
Hi @tanmoy27112000 , assign me the issue

**Comment by avirupnandi1** [comment]
I would like to work on that issue under JWOC, please assign me

**Comment by tanmoy27112000** [comment]
@avirupnandi1 sure you can work on this issue. The PR that you have created before is not the right one. you need to create a customisable grid view widget with a hover effect. Think of it as this design 
https://getbootstrap.com/docs/5.3/examples/album/

with a hover effect, you need to create widget compatible with desktop ,tab and mobile view
